-d C:\Workspace\tang-nano-9k-HDMI\impl\gwsynthesis\hdmi.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Workspace\tang-nano-9k-HDMI\src\hdmi.cst
-cfg C:\Workspace\tang-nano-9k-HDMI\impl\pnr\device.cfg
-sdc C:\Workspace\tang-nano-9k-HDMI\src\nano_20k_video.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
